# Generated by Django 3.2.6 on 2021-10-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=194, verbose_name='Nome completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=194, null=True, verbose_name='E-mail')),
                ('usuario', models.CharField(max_length=50, verbose_name='Login')),
                ('senha', models.CharField(max_length=15, verbose_name='Senha')),
                ('confirme_senha', models.CharField(max_length=15, verbose_name='Confirme a Senha')),
                ('clinica_id', models.CharField(max_length=10, verbose_name='Id clinica')),
                ('observacao', models.CharField(max_length=200, verbose_name='Observacao')),
            ],
        ),
    ]
