# Generated by Django 3.2.6 on 2021-10-15 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criar_operador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operador',
            options={'verbose_name': 'Operador', 'verbose_name_plural': 'Operadores'},
        ),
        migrations.AlterModelTable(
            name='operador',
            table='operador',
        ),
    ]
