# Generated by Django 3.2.6 on 2021-08-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_especialidade', models.CharField(max_length=194, verbose_name='Especialidade')),
            ],
        ),
    ]
