# Generated by Django 3.2.6 on 2021-09-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidade',
            name='nome_especialidade',
            field=models.CharField(default=2, max_length=194, verbose_name='Especialidade'),
            preserve_default=False,
        ),
    ]
