# Generated by Django 3.2.6 on 2021-08-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=194, verbose_name='Nome da clínica')),
                ('cnpj', models.CharField(max_length=100, verbose_name='CPF')),
                ('site', models.CharField(max_length=50, verbose_name='Site')),
                ('endereco', models.CharField(max_length=194, verbose_name='Endereço (rua, número e bairro)')),
                ('cidade', models.CharField(max_length=194, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=194, verbose_name='Estado')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone de contato')),
                ('responsavel', models.CharField(max_length=194, verbose_name='Nome do responsável')),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
                'db_table': 'clinica',
            },
        ),
    ]
