# Generated by Django 3.2.6 on 2021-08-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=194, verbose_name='Nome completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('endereço', models.CharField(max_length=194, verbose_name='Endereço (rua, número e bairro)')),
                ('cidade', models.CharField(max_length=194, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=194, verbose_name='Estado')),
                ('email', models.EmailField(blank=True, max_length=194, null=True, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
            },
        ),
    ]
