# Generated by Django 3.2.6 on 2021-08-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('MASCULINO', 'masculino'), ('FEMININO', 'feminino')], default=None, max_length=9, verbose_name='Sexo'),
        ),
    ]
