# Generated by Django 3.2.6 on 2021-09-26 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0001_initial'),
        ('pacientes', '0004_alter_paciente_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicas.clinica'),
        ),
    ]
