# Generated by Django 3.2.6 on 2021-09-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('CONSULTADO', 'Consultado'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=126, verbose_name='Status de agendamento'),
        ),
    ]
