# Generated by Django 3.2.6 on 2021-09-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicos',
            options={'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.AddField(
            model_name='medicos',
            name='email',
            field=models.EmailField(blank=True, max_length=194, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default=None, max_length=9, verbose_name='Sexo'),
        ),
        migrations.AlterModelTable(
            name='medicos',
            table='medicos',
        ),
    ]
