# Generated by Django 3.2.6 on 2021-09-26 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0001_initial'),
        ('medicos', '0002_auto_20210901_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicos',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicas.clinica'),
        ),
    ]
