# Generated by Django 3.2.6 on 2021-09-27 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_auto_20210927_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disponibilidade',
            old_name='status',
            new_name='disponivel',
        ),
    ]
