# Generated by Django 3.2.6 on 2021-09-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0004_rename_status_disponibilidade_disponivel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponibilidade',
            options={'verbose_name': 'Disponibilidade', 'verbose_name_plural': 'Disponibilidades'},
        ),
        migrations.AlterModelOptions(
            name='medicos',
            options={'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.AlterField(
            model_name='disponibilidade',
            name='hora',
            field=models.TimeField(verbose_name='Horário disponível'),
        ),
        migrations.AlterModelTable(
            name='disponibilidade',
            table='disponibilidade',
        ),
        migrations.AlterModelTable(
            name='medicos',
            table='medicos',
        ),
    ]
