# Generated by Django 3.2.6 on 2021-10-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_medicos_clinica'),
        ('medicos', '0005_auto_20210930_1817'),
    ]

    operations = [
    ]
