# Generated by Django 3.2.6 on 2021-10-08 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0001_initial'),
        ('medicos', '0006_merge_0003_medicos_clinica_0005_auto_20210930_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidade',
            name='clinica',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='clinicas.clinica'),
            preserve_default=False,
        ),
    ]
